"""initial_migration_create_tables

Revision ID: 9dfa545cf7f0
Revises: 
Create Date: 2025-05-21 10:02:50.010266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfa545cf7f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id_original', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('history_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_entry_id'], ['history_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_item')
    op.drop_table('history_item')
    op.drop_table('template')
    op.drop_table('history_entry')
    # ### end Alembic commands ###
